#question2
par(mfrow=c(2,2))
N <-1000
A <-c(0,pi/3,pi/2,pi)
p <-cos(A)
b <-runif(N,min = 0,max = 2*pi)
X <-cos(b)
Y <-cos(A[1]+b)
plot(X,Y,col='blue')
title(main ="老=1")
X <-cos(b)
Y <-cos(A[2]+b)
plot(X,Y,col='blue')
title(main ="老=1/2")
X <-cos(b)
Y <-cos(A[3]+b)
plot(X,Y,col='blue')
title(main ="老=﹟2/2")
X <-cos(b)
Y <-cos(A[4]+b)
plot(X,Y,col='blue')
title(main ="老=0")